version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'monthly'
    commit-message:
      prefix: '[DEPENDA-BOT] '

  # Maintain dependencies for npm
  # only update dependencies that are very urgent
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    commit-message:
      prefix: '[DEPENDA-BOT] '
    open-pull-requests-limit: 3
    labels:
      - 'dependency alerts'
      - 'security'
